version: '3.5'

services:
  influxdb:
    image: influxdb
    restart: always
    networks:
      - assignment-network
    ports:
      - 8086:8086
  assingmentproxy:
    image: yapilyassignment/assignmentproxy
    restart: always
    networks:
      - assignment-network
    ports:
      - 8080:8080
    environment:
      KPI_DATABASE_URL: http://influxdb:8086
      KPI_DATABASE_USERNAME: root
      KPI_DATABASE_PASSWORD: root
networks:
  assignment-network:
    name: assignment-network